"""File storage abstraction. Default: local disk. Future: S3/OSS."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class FileStorage(Protocol):
    async def save(self, data: bytes, key: str) -> str: ...
    async def read(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...
    def get_url(self, key: str) -> str: ...
