/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_v1_suppliers_get"];
        put?: never;
        /** Create Supplier */
        post: operations["create_supplier_api_v1_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier */
        get: operations["get_supplier_api_v1_suppliers__supplier_id__get"];
        /** Update Supplier */
        put: operations["update_supplier_api_v1_suppliers__supplier_id__put"];
        post?: never;
        /** Delete Supplier */
        delete: operations["delete_supplier_api_v1_suppliers__supplier_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Purchases */
        get: operations["list_purchases_api_v1_purchases_get"];
        put?: never;
        /** Create Purchase */
        post: operations["create_purchase_api_v1_purchases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases/{purchase_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Purchase */
        get: operations["get_purchase_api_v1_purchases__purchase_id__get"];
        /** Update Purchase */
        put: operations["update_purchase_api_v1_purchases__purchase_id__put"];
        post?: never;
        /** Delete Purchase */
        delete: operations["delete_purchase_api_v1_purchases__purchase_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PurchaseCreate */
        PurchaseCreate: {
            /** Supplier Id */
            supplier_id?: string | null;
            /** Total Amount */
            total_amount?: number | string | null;
            /** Purchase Time */
            purchase_time?: string | null;
            /** Notes */
            notes?: string | null;
            /** Items */
            items?: components["schemas"]["PurchaseItemCreate"][];
        };
        /** PurchaseItemCreate */
        PurchaseItemCreate: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | string;
            /** Unit */
            unit?: string | null;
            /** Unit Price */
            unit_price: number | string;
            /** Category */
            category?: string | null;
            /** Brand */
            brand?: string | null;
        };
        /** PurchaseItemOut */
        PurchaseItemOut: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: string;
            /** Unit */
            unit?: string | null;
            /** Unit Price */
            unit_price: string;
            /** Category */
            category?: string | null;
            /** Brand */
            brand?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Purchase Id
             * Format: uuid
             */
            purchase_id: string;
        };
        /**
         * PurchaseListItem
         * @description Lighter view for list pages — omits items to keep responses small.
         */
        PurchaseListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Supplier Id */
            supplier_id: string | null;
            /** Total Amount */
            total_amount: string | null;
            /**
             * Purchase Time
             * Format: date-time
             */
            purchase_time: string;
            /** Manual Adjustment */
            manual_adjustment: boolean;
            /** Item Count */
            item_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PurchaseOut */
        PurchaseOut: {
            /** Supplier Id */
            supplier_id?: string | null;
            /** Total Amount */
            total_amount?: string | null;
            /**
             * Purchase Time
             * Format: date-time
             */
            purchase_time: string;
            /** Notes */
            notes?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Receipt Image Path */
            receipt_image_path: string | null;
            /** Ocr Provider */
            ocr_provider: string | null;
            /** Manual Adjustment */
            manual_adjustment: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items?: components["schemas"]["PurchaseItemOut"][];
        };
        /** PurchaseUpdate */
        PurchaseUpdate: {
            /** Supplier Id */
            supplier_id?: string | null;
            /** Total Amount */
            total_amount?: number | string | null;
            /** Purchase Time */
            purchase_time?: string | null;
            /** Notes */
            notes?: string | null;
            /** Manual Adjustment */
            manual_adjustment?: boolean | null;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Business Hours */
            business_hours?: string[] | null;
            /** Contact Info */
            contact_info?: string | null;
            /** Preferences */
            preferences?: string[] | null;
            /** Notes */
            notes?: string | null;
        };
        /** SupplierOut */
        SupplierOut: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Business Hours */
            business_hours?: string[] | null;
            /** Contact Info */
            contact_info?: string | null;
            /** Preferences */
            preferences?: string[] | null;
            /** Notes */
            notes?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Business Hours */
            business_hours?: string[] | null;
            /** Contact Info */
            contact_info?: string | null;
            /** Preferences */
            preferences?: string[] | null;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_suppliers_api_v1_suppliers_get: {
        parameters: {
            query?: {
                /** @description 模糊搜索名称/地址/备注 */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_api_v1_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_api_v1_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_api_v1_suppliers__supplier_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_api_v1_suppliers__supplier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_purchases_api_v1_purchases_get: {
        parameters: {
            query?: {
                supplier_id?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_purchase_api_v1_purchases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_purchase_api_v1_purchases__purchase_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_purchase_api_v1_purchases__purchase_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_purchase_api_v1_purchases__purchase_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
