"""init schema

Revision ID: fd769eaac1a8
Revises: 
Create Date: 2026-06-16 21:49:11.813389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd769eaac1a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('business_hours', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('preferences', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('receipt_image_path', sa.Text(), nullable=True),
    sa.Column('ocr_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_provider', sa.String(length=50), nullable=True),
    sa.Column('manual_adjustment', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchases_supplier', 'purchases', ['supplier_id'], unique=False)
    op.create_index('idx_purchases_time', 'purchases', ['purchase_time'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_name', 'purchase_items', ['name'], unique=False)
    op.create_index('idx_items_purchase', 'purchase_items', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_items_purchase', table_name='purchase_items')
    op.drop_index('idx_items_name', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('idx_purchases_time', table_name='purchases')
    op.drop_index('idx_purchases_supplier', table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
